"""rename price to unit_price

Revision ID: 141894c96f4c
Revises: c47afbb80b66
Create Date: 2026-08-27 00:34:30.933138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141894c96f4c'
down_revision: Union[str, Sequence[str], None] = 'c47afbb80b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('unit_price', sa.Float(), nullable=False))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orders', 'unit_price')
    # ### end Alembic commands ###
